---
- name: Install certbot (requirement for Letsencrypt)
  apt:
    name: certbot
    state: present

- name: Install python3-certbot-nginx (requirement for Letsencrypt)
  apt:
    name: python3-certbot-nginx
    state: present


#You can configure your other servers with just copying this job
- name: Create jenkins cert and deploy to nginx
  shell:
    sudo certbot run -n  --nginx --agree-tos -d {{ server_name }} -d www.{{ server_name }} -m justemail@gmail.com --redirect



- name: Create nexus cert and deploy to nginx
  shell:
    sudo certbot run -n  --nginx --agree-tos -d {{ server_name_1 }} -d www.{{ server_name_1 }} -m justemail@gmail.com --redirect








